### ISSUE TITLE
Commands keyboard bindings

### ISSUE THREAD

**Issue by daylioti** [daylioti/docker-commander#11]
It will be nice to have possibility to execute some command using keyboard events.
F.e build some gulp by <C-b> or download database <C-d>

```yaml
- name: gulp build
  bind: <C-b>
  exec: 
   cmd: gulp build
    connect:
      container_name: ubuntu
```
